apiVersion: batch/v1
kind: CronJob
metadata:
  name: deletefailedsuccpod-dep
spec:
  schedule: "0 0 * * 1"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: incluster-sa
          containers:
          - name: deletefailedsuccpod-dep
            image: vinayaks439/deletesucceededfailedpo:v1
            imagePullPolicy: Always
          restartPolicy: OnFailure
