apiVersion: batch/v1
kind: CronJob
metadata:
  name: deletefailedsuccpod_dep
spec:
  schedule: "0 0 * * 1"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: incluster-sa
          containers:
          - name: deletefailedsuccpod_dep
            image: vinayaks439/deletesucceededfailedpo:v1
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
